Import("env")

env_test = env.Clone()

env_test.Append(CPPPATH=["/home/sarah/pub/gtest-1.7.0/include"],
                LIBS=["pthread"])

env_test.Program("unittest",
                 ["unittest.cpp",
                  "/home/sarah/pub/gtest-1.7.0/make/gtest.a",
                  "/home/sarah/pub/gtest-1.7.0/make/gtest_main.a"])
